[package]
name = "clink"
version = "0.0.1"
edition = "2018"
authors = ["Kathryn Long <squeeself@gmail.com>"]
publish = false

[dependencies]
ink = { path = "ink" }
clap = "2.32"
anyhow = "1"
log = "0.4"
simple-logging = "2"

[workspace]